- hosts: localhost
  become: true
  vars:
    source_key: "./secrets/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    source_pub_key: "./secrets/id_ed25519.pub"
    dest_pub_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519.pub"
    source_npmrc: "./secrets/.npmrc"
    dest_npmrc: "{{ lookup('env', 'HOME') }}/.npmrc"
    source_openai_api_key: "./secrets/.openai-api-key"
    dest_openai_api_key: "{{ lookup('env', 'HOME') }}/.openai-api-key"
    source_feed_access_token: "./secrets/.feed-access-token"
    dest_feed_access_token: "{{ lookup('env', 'HOME') }}/.feed-access-token"
  tasks:
    - name: Ensure .ssh directory exists.
      file:
        dest: "{{ dest_key | dirname }}"
        mode: 0700
        state: directory
    - name: Install ssh key
      copy:
        src: "{{ source_key }}"
        dest: "{{ dest_key }}"
        mode: 0600
    - name: Install ssh pub key
      copy:
        src: "{{ source_pub_key }}"
        dest: "{{ dest_pub_key }}"
        mode: 0600
    - name: Set authorized key took from file
      authorized_key:
        user: "{{ lookup('env', 'USER') }}"
        state: present
        key: "{{ lookup('file', item) }}"
      with_fileglob:
        - ./secrets/id_ed25519.pub
    - name: Give ownership of .ssh to user
      shell: chown -R {{ lookup('env', 'USER') }}:users  /home/{{ lookup('env', 'USER') }}/.ssh
    - name: Install npmrc 
      copy:
        src: "{{ source_npmrc }}"
        dest: "{{ dest_npmrc }}"
        mode: 0600
    - name: Give ownership to npmrc
      shell: chown {{ lookup('env', 'USER') }}:users  /home/{{ lookup('env', 'USER') }}/.npmrc
    - name: Install openai-api-key
      copy:
        src: "{{ source_openai_api_key }}"
        dest: "{{ dest_openai_api_key }}"
        mode: 0600
    - name: Give ownership to openai-api-key
      shell: chown {{ lookup('env', 'USER') }}:users  /home/{{ lookup('env', 'USER') }}/.openai-api-key
    - name: Install feed-access-token
      copy:
        src: "{{ source_feed_access_token }}"
        dest: "{{ dest_feed_access_token }}"
        mode: 0600
    - name: Give ownership to feed-access-token
      shell: chown {{ lookup('env', 'USER') }}:users  /home/{{ lookup('env', 'USER') }}/.feed-access-token
