{ pkgs, config, osConfig, ... }:

with config.colorScheme.palette;

{
    wayland.windowManager.hyprland = {
        enable = true;
        settings = {
            autogenerated = 0;
            workspace = [
                "DP-1,1, persistence:true"
                "DP-1,2, persistence:true"
                "DP-1,3, persistence:true"
                "DP-1,4, persistence:true"
                "DP-1,5, persistence:true"
                "DP-1,6, persistence:true"
                "HDMI-A-1,7, persistence:true"
                "HDMI-A-1,8, persistence:true"
                "DP-2,9, persistence:true"
            ];
            exec-once = [
                ''${pkgs.swww}/bin/swww init''
                ''${pkgs.waybar}/bin/waybar ''
                ''${pkgs.networkmanagerapplet}/bin/nm-applet''
                ''${pkgs.swayidle}/bin/swayidle -w timeout 1200 '${pkgs.swaylock-effects}/bin/swaylock -f' timeout 2400 'systemctl suspend' before-sleep '${pkgs.swaylock-effects}/bin/swaylock -f' &''
            ];
            monitor = map
              (m:
                let
                  resolution = "${toString m.width}x${toString m.height}@${toString m.refreshRate}";
                  position = "${toString m.x}x${toString m.y}";
                  scale = "${toString m.scale}";
                in
                "${m.name},${if m.enabled then "${resolution},${position},${scale}" else "disable"}"
              ) (osConfig.monitors);
            input = {
                kb_layout = "us";
                follow_mouse = 1;
                touchpad = {
                    natural_scroll = "yes";
                };
                sensitivity = 0;
            };
            general = {
                gaps_in = 5;
                gaps_out = 10;
                border_size = 2.5;
                "col.active_border" = "rgba(${base0E}ff) rgba(${base0D}ff) 45deg";
                "col.inactive_border" = "rgba(${base03}ff)";
                layout = "dwindle";
                allow_tearing = false;
            };
            misc = {
                disable_hyprland_logo = "yes";
            };
            decoration = {
                rounding = 10;
                blur = {
                    enabled = true;
                    size = 3;
                    passes = 1;
                    vibrancy = 0.1696;
                };
                drop_shadow = true;
                shadow_range = 4;
                shadow_render_power = 3;
                "col.shadow" = "rgba(1a1a1aee)";
            };
            animations = {
                enabled = "yes";
                bezier = "myBezier, 0.05, 0.9, 0.1, 1.05";
                animation = [
                    " windows, 1, 7, myBezier"
                    " windowsOut, 1, 7, default, popin 80%"
                    " border, 1, 10, default"
                    " borderangle, 1, 8, default"
                    " fade, 1, 7, default"
                    " workspaces, 1, 6, default"
                ];
            };
            dwindle = {
                pseudotile = "yes";
                preserve_split = "yes";
            };
            master = {
                new_is_master = true;
            };
            gestures = {
                workspace_swipe = "off";
            };
            "device:epic-mouse-v1" = {
                sensitivity = -0.5;
            };
            windowrulev2 = [
                " opacity 0.80 0.80,class:^(kitty)$"
                " opacity 0.95 0.95,class:^(thunar)$"
            ];
            binde = [
                " CTRL, HOME, exec, pamixer -i 10"
                " CTRL, END, exec, pamixer -d 10"
                " CTRL, Next, exec, playerctl previous"
                " CTRL, Prior, exec, playerctl next"
            ];
            "$mainMod" = "SUPER";
            bind = [
                " $mainMod, Return, exec,kitty --title Kitty tmux"
                " $mainMod, C, killactive, "
                " $mainMod, B, exec, firefox "
                " $mainMod, Q, exit, "
                " $mainMod, M, exec, swaylock && systemctl suspend"
                " $mainMod, E, exec, thunar"
                " $mainMod, V, togglefloating, "
                " $mainMod, F, fullscreen, # fullscreen"
                " $mainMod, P, exec, wofi --allow-images --show drun"
                " $mainMod, D, pseudo, # dwindle"
                " $mainMod, T, togglesplit, # dwindle"
                '' SHIFT, Print, exec , grim -g "$(slurp)" - | swappy -f - ''
                '' , Print, exec , grim -g "$(slurp)" - | wl-copy ''
                " SUPER_SHIFT, F12, exec, shutdown now"
                " SUPER_SHIFT, F11, exec, systemctl reboot"
                " $mainMod, F12, exec, swww-randomizer"
                " $mainMod, left, movefocus, l"
                " $mainMod, right, movefocus, r"
                " $mainMod, up, movefocus, u"
                " $mainMod, down, movefocus, d"
                " $mainMod, H, movefocus, l"
                " $mainMod, L, movefocus, r"
                " $mainMod, K, movefocus, u"
                " $mainMod, J, movefocus, d"
                " $mainMod, F1, workspace, 1"
                " $mainMod, F1, exec, firefox --new-window"
                " $mainMod, F2, workspace, 2"
                " $mainMod, F2, exec, kitty --title Kitty tmux"
                " $mainMod, F3, workspace, 3"
                " $mainMod, F3, exec, firefox --new-window"
                " $mainMod, F4, workspace, 4"
                " $mainMod, F4, exec, dbeaver"
                " $mainMod, F5, workspace, 5"
                " $mainMod, F5, exec, rider"
                " $mainMod, F6, workspace, 6"
                " $mainMod, F6, exec, joplin-desktop"
                " $mainMod, F7, workspace, 7"
                " $mainMod, F7, exec, thunderbird"
                " $mainMod, F8, workspace, 8"
                " $mainMod, F8, exec, brave --app=https://teams.microsoft.com/"
                " $mainMod, F9, workspace, 9"
                " $mainMod, F9, exec, brave --app=https://music.youtube.com/"
                " $mainMod SHIFT, F9, exec, brave --app=https://app.plex.tv/desktop/#!/"
                " $mainMod, 1, workspace, 1"
                " $mainMod, 2, workspace, 2"
                " $mainMod, 3, workspace, 3"
                " $mainMod, 4, workspace, 4"
                " $mainMod, 5, workspace, 5"
                " $mainMod, 6, workspace, 6"
                " $mainMod, 7, workspace, 7"
                " $mainMod, 8, workspace, 8"
                " $mainMod, 9, workspace, 9"
                " $mainMod, 0, workspace, 10"
                " $mainMod, mouse_down, workspace, e+1"
                " $mainMod, mouse_up, workspace, e-1"
                " $mainMod SHIFT, 2, movetoworkspace, 2"
                " $mainMod SHIFT, 3, movetoworkspace, 3"
                " $mainMod SHIFT, 4, movetoworkspace, 4"
                " $mainMod SHIFT, 5, movetoworkspace, 5"
                " $mainMod SHIFT, 6, movetoworkspace, 6"
                " $mainMod SHIFT, 7, movetoworkspace, 7"
                " $mainMod SHIFT, 8, movetoworkspace, 8"
                " $mainMod SHIFT, 9, movetoworkspace, 9"
                " $mainMod SHIFT, 0, movetoworkspace, 10"
                " CTRL, Backslash, exec, playerctl play-pause"
                " , xf86audioraisevolume, exec, pamixer -i 10"
                " , xf86audiolowervolume, exec, pamixer -d 10"
                " , xf86AudioMicMute, exec, pactl set-source-mute @DEFAULT_SOURCE@ toggle"
                " , xf86audioMute, exec, pamixer --default-source -t"
                " , xf86audioPlay, exec, playerctl play-pause"
                " , xf86audioNext, exec, playerctl next"
                " , xf86audioPre, exec, playerctl previous"
            ];
        };
    };
}
