require("chatgpt").setup()
require("colorizer").setup()
require("Comment").setup()
require("fidget").setup({})
require("noice").setup({})
require("scrollbar").setup({})
require("scrollbar.handlers.gitsigns").setup()
require("nvim-autopairs").setup({ check_ts = true })
require('mini.ai').setup { n_lines = 500 }
require('mini.surround').setup()
