require("chatgpt").setup()
require("colorizer").setup()
require("Comment").setup()
require("fidget").setup({})
require("scrollbar").setup()
require("scrollbar.handlers.gitsigns").setup()
require("nvim-autopairs").setup({ check_ts = true, ts_config = { java = false }})
require('mini.ai').setup { n_lines = 500 }
require('mini.surround').setup()
require('lualine').setup({ options = { icons_enabled = true, theme = 'base16', component_separators = '', section_separators = '' }})
